### ISSUE TITLE
Using Calamari's uw3-modern-english model

### ISSUE THREAD

**Issue by kylekyle** [OCR4all/OCR4all#133]
Love OCRD, by the way. Thanks for all the work you've put into it! 

The `uw3-modern-english` model is relatively new, so it is not in the 0.3 models for Calamari. What's the best way to make the model compatible with OCRD (or to make OCRD compatible with the model)? The link to the original dataset is broken, so I'm not sure re-training is an option ...

Any tips would be appreciated. Thanks!

**Comment by maxnth** [comment]
Hi, I'm a bit confused about the issue as OCR4all uses Calamari v1.0.5 since release [0.3.0](https://github.com/OCR4all/OCR4all/releases/tag/0.3.0) (the yet to be released 0.6.0 will use Calamari >v2, the staging version for it is already available at our [Dockerhub](https://hub.docker.com/r/uniwuezpd/ocr4all)) so all recent versions should usually be compatible with the above mentioned model.
While we're already working on making OCR4all compatible with OCR-D in future versions (v1.0 upwards) we currently don't offer any integration of OCR-D.

In case the question is about using the model with [ocrd_calamari](https://github.com/OCR-D/ocrd_calamari) in an OCR-D workflow I can't really help with that but AFAIK they also already support Calamari >1.0.

**Comment by kba** [comment]
@kylekyle Glad you're interested in OCR-D but as @maxnth pointed out, you should open an issue with https://github.com/OCR-D/ocrd_calamari. ocrd_calamari is still relying on calamari 1.0.x, so the models in https://github.com/Calamari-OCR/calamari_models/ in their most recent form won't work with ocrd-calamari. However you can use the older state of the models, the `uw3-modern-english` model at https://github.com/Calamari-OCR/calamari_models/commit/16630e34ed77e7d6fa735c2505c82c081dbeb42a#diff-59416adf37dcfc39f6f79d9607f28ef3e4e6b45863fcfef71c0f604359b342ba still works with ocrd-calamari.
