### ISSUE TITLE
Instruction for installation from source

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/OCR4all#134]
I'm very curious to explore the new release: Is there a guide on how to install from source? [Here](https://github.com/OCR4all/getting_started) a "setup guide" is mentioned which I cannot find:

> To get started, it is recommended to download the entire repository ("Clone or download" -> "Download ZIP"), install OCR4all by following the setup guide, and then get some hand-on experience by working with the examples covered in the short user guide.

Thanks!

**Comment by maxnth** [comment]
Installing from source isn't really advised (because managing the external dependencies for Calamari, kraken, ... can be a hassle) but if you really want to, you could follow the instructions defined in the Dockerfiles [here](https://github.com/OCR4all/docker_image) and [here](https://github.com/OCR4all/docker_base_image).

Just directly using the Docker images provided by would probably be a lot easier. You can use `uniwuezpd/ocr4all:latest` or `uniwuezpd/ocr4all:0.6.1` to get the latest release of OCR4all.

**Comment by alexander-winkler** [comment]
I was suspecting that I might have to mimic the Dockerfile – which could be a bit too much hassle. Thank you for the information on the docker tag for the `0.6.1` release. That will definitely help.

I am aware of the guide. But it explains just the docker installation and not the installation from source (an approach the 'clone or download' -> 'download zip' approach would suggest). So I wanted to make sure I don't miss anything.

**Comment by maxnth** [comment]
>I am aware of the guide. But it explains just the docker installation and not the installation from source (an approach the 'clone or download' -> 'download zip' approach would suggest).

I agree that this isn't as precise as it could be. I'll forward it to my colleagues who are currently working on updating the guides.
