### ISSUE TITLE
Word-based PageXML Output / Wortweise PageXML Ebene in der Ausgabe

### ISSUE THREAD

**Issue by FLE92** [OCR4all/OCR4all#25]
Liebe Kollegen, 

es würde uns sehr helfen wenn künftig die PageXML-Daten der Ausgabe eine Wortebene enthielten. 

Vielen Dank für Eure Mühe im Voraus! 

Schöne Grüße aus München 
Florian Landes

**Comment by NesbiDevelopment** [comment]
Schönen guten Tag, leider ist dieses Issue etwas übersehen worden.
Könnten Sie erleutern was sie genau mit Ausgabe auf Wortebene meinen?

Meinen Sie damit die Ausgabe der Zeichenerkennung in "Word" Blocks mit Coordinaten statt in "TextEquivs"? (PageXML)

----------
Good day! I'm sorry that we overlooked your issue.
Could you explain what exactly you mean with output on word level?

DO you mean the output of the OCR in "Word" blocks with coords, instead of "TextEquivs"? (PageXML)

**Comment by maxnth** [comment]
This feature is now available in [release 0.3.0](https://github.com/OCR4all/OCR4all/releases/tag/0.3.0)

**Comment by kba** [comment]
@maxnth You might want to publish a changelog with the release, this is a significant improvement IMHO.

**Comment by maxnth** [comment]
@kba 
Currently working on it and we'll send out a mail with all information to the OCR4all mailing list today as well :smile:
